#!/bin/sh /etc/rc.common
 
START=90
STOP=01
USE_PROCD=1
 
start_service() {
        procd_open_instance
        procd_set_param command /bin/sh "/usr/bin/set_isolation"
        procd_append_param command daemon
        procd_set_param pidfile /var/run/isolation.pid
        procd_set_param term_timeout 1
        procd_set_param stdout 1
        procd_close_instance
}
 
stop_service() {
        ebtables -F
}

restart_service() {
        stop
        start
}

service_triggers() {
        procd_add_reload_trigger "isolation" restart
}
